"""
Notebook environment integration.

Provides zero-friction activation for:

  - Jupyter / IPython  – via ``ip.ast_transformers`` (official public API)
  - Marimo             – via a ``marimo._ast.compiler.ast_compile`` patch applied
                         at notebook module-import time

Usage
-----
Jupyter / IPython (in a notebook cell):

    from tracker import init_jupyter
    rt = init_jupyter()           # auto-detects the running IPython shell
    # All subsequent cells are tracked automatically

Marimo (at module level in the .py notebook, before app = marimo.App(...)):

    import builtins as _builtins
    from tracker.kernel_hooks import patch_marimo_ast_compile, _NoOpRuntime
    _builtins._provtrack_runtime = _NoOpRuntime()
    patch_marimo_ast_compile()

    app = marimo.App(width="medium")

    @app.cell
    def _():
        from tracker import init_marimo
        rt = init_marimo(...)   # replaces _NoOpRuntime with the real tracker
        ...
"""

from __future__ import annotations

import ast
import builtins
import uuid
from pathlib import Path
from typing import Optional

from tracker.ast_rewriter import ProvTrackTransformer
from tracker.runtime import RuntimeTracker
from tracker.storage import DuckDBSQLiteBackend


# Shared transformer instance (stateless — safe for concurrent compilation).
_TRANSFORMER = ProvTrackTransformer()

# Module-level runtime reference used by the generated __import__ lookup.
# Starts as _NoOpRuntime; replaced by init_jupyter / init_marimo.
_runtime: object = None  # forward declaration — replaced after _NoOpRuntime is defined


# ------------------------------------------------------------------
# No-op placeholder runtime
# ------------------------------------------------------------------

class _NoOpRuntime:  # noqa: E302
    """
    Passthrough placeholder set in ``builtins._provtrack_runtime`` before the
    real ``RuntimeTracker`` is ready.

    Prevents ``NameError`` from transformed cell code that runs before
    ``init_marimo()`` has been called (e.g. path-setup calls in the init cell
    itself that happen before the tracker is created).
    """
    def trace_step(self, *, func, func_name, raw_line, args, kwargs):
        return func(*args, **kwargs)


# Initialise _runtime to the no-op now that the class is defined.
_runtime = _NoOpRuntime()


# ------------------------------------------------------------------
# Jupyter / IPython
# ------------------------------------------------------------------

def init_jupyter(
    ip_shell=None,
    db_path: str | Path = "provenance.db",
    artifact_dir: str | Path = "artifacts",
    agent_id: Optional[str] = None,
    history_name: Optional[str] = None,
    branch_name: str = "main",
) -> RuntimeTracker:
    """
    Register ProvTrack in the active IPython kernel.

    Parameters
    ----------
    ip_shell:
        IPython ``InteractiveShell`` instance.  If *None*, auto-detected via
        ``IPython.get_ipython()``.
    db_path:
        Path for the DuckDB / SQLite provenance database.
    artifact_dir:
        Directory where DataFrame Parquet snapshots are written.
        Defaults to ``"artifacts"`` relative to the working directory.
    agent_id:
        Override the agent identifier (defaults to the OS username).
    history_name:
        Human-readable title for the analysis session.
        Defaults to the auto-generated history UUID.
    branch_name:
        Name for the initial analysis branch.  Defaults to ``"main"``.

    Returns
    -------
    RuntimeTracker
        The active tracker instance (also stored as ``_provtrack_runtime``
        in the notebook's user namespace).
    """
    if ip_shell is None:
        try:
            from IPython import get_ipython
            ip_shell = get_ipython()
        except ImportError:
            pass
    if ip_shell is None:
        raise RuntimeError(
            "No active IPython shell found. "
            "Call init_jupyter() from inside a running Jupyter notebook."
        )

    storage = DuckDBSQLiteBackend(db_path=db_path, artifact_dir=artifact_dir)
    runtime = RuntimeTracker(
        storage=storage,
        session_id=str(uuid.uuid4()),
        agent_id=agent_id,
        history_name=history_name,
        branch_name=branch_name,
    )

    # Make the runtime reachable via the module-level _runtime (used by the
    # __import__-based lookup generated by ProvTrackTransformer) and also via
    # the legacy _provtrack_runtime name in the IPython user namespace.
    global _runtime
    _runtime = runtime
    ip_shell.user_ns["_provtrack_runtime"] = runtime

    # Register transformer only once (guard against double-init)
    if not any(isinstance(t, ProvTrackTransformer) for t in ip_shell.ast_transformers):
        ip_shell.ast_transformers.append(ProvTrackTransformer())

    return runtime


# ------------------------------------------------------------------
# Marimo
# ------------------------------------------------------------------

def init_marimo(
    db_path: str | Path = "provenance.db",
    artifact_dir: str | Path = "artifacts",
    agent_id: Optional[str] = None,
    history_name: Optional[str] = None,
    branch_name: str = "main",
) -> RuntimeTracker:
    """
    Create a ``RuntimeTracker`` for a Marimo reactive notebook and register it
    in ``builtins`` so that all transformed cell code can resolve
    ``_provtrack_runtime`` at runtime.

    This function must be called from the init cell (the first cell in the
    notebook).  The AST transformation itself is activated separately at
    module level via ``patch_marimo_ast_compile()``.

    Parameters
    ----------
    db_path:
        Path for the DuckDB / SQLite provenance database.
    artifact_dir:
        Directory where DataFrame Parquet snapshots are written.
    agent_id:
        Override the agent identifier (defaults to the OS username).
    history_name:
        Human-readable title for the analysis session.
    branch_name:
        Name for the initial analysis branch.  Defaults to ``"main"``.

    Design note on Marimo's reactive DAG
    ------------------------------------
    Marimo re-executes downstream cells automatically when upstream outputs
    change.  Each ProvTrack node stores the ``session_id`` so that cascade
    re-executions within the same session can be identified and parent-child
    links in the edges table map directly onto Marimo's execution graph.
    """
    storage = DuckDBSQLiteBackend(db_path=db_path, artifact_dir=artifact_dir)
    session_id = str(uuid.uuid4())
    runtime = RuntimeTracker(
        storage=storage,
        session_id=session_id,
        agent_id=agent_id,
        history_name=history_name,
        branch_name=branch_name,
    )

    # Replace the _NoOpRuntime with the real tracker.
    # module-level _runtime: used by the __import__-based lookup emitted by
    #   ProvTrackTransformer — works in any exec() context regardless of how
    #   __builtins__ is set up (Marimo AppScriptRunner uses a dict copy).
    # builtins._provtrack_runtime: kept for backward compatibility with any
    #   existing code that reads this attribute directly.
    global _runtime
    _runtime = runtime
    builtins._provtrack_runtime = runtime  # type: ignore[attr-defined]

    return runtime


# ------------------------------------------------------------------
# Marimo ast_compile patch
# ------------------------------------------------------------------

_MARIMO_PATCHED = False


def patch_marimo_ast_compile() -> None:
    """
    Patch ``marimo._ast.compiler.ast_compile`` to apply ``ProvTrackTransformer``
    to every cell's ``ast.Module`` before it is compiled to bytecode.

    **Must be called at module level** in the Marimo ``.py`` notebook, before
    the ``app = marimo.App(...)`` line.  Marimo compiles all ``@app.cell``
    bodies at module-import time; a patch applied later (e.g. inside a cell)
    would be too late.

    Why ``ast_compile`` and not ``module_compile``
    -----------------------------------------------
    ``compile_cell`` calls ``module_compile(code)`` first, then runs
    ``ScopedVisitor`` to build Marimo's reactive dependency graph, then calls
    ``ast_compile(module, filename, "exec", ...)`` to generate bytecode.

    Patching ``ast_compile`` (the bytecode step) means:

    * Marimo's ``ScopedVisitor`` sees the **original** AST — the reactive DAG
      is correct and ``_provtrack_runtime`` never appears as a cell dependency.
    * The **transformed** code (with ``_provtrack_runtime.trace_step(...)``
      wrappers) is what ends up in the compiled bytecode that actually runs.
    """
    global _MARIMO_PATCHED
    if _MARIMO_PATCHED:
        return
    _MARIMO_PATCHED = True

    try:
        from marimo._ast import compiler as _mc
    except ImportError:
        return  # Marimo not installed; nothing to do

    _original_ast_compile = _mc.ast_compile

    def _patched_ast_compile(source, filename, mode, *args, **kwargs):
        if isinstance(source, ast.Module) and mode == "exec":
            try:
                _TRANSFORMER.visit(source)        # mutates node.body in-place
                ast.fix_missing_locations(source)
            except Exception:
                pass  # fall through on any error — never break cell compilation
        return _original_ast_compile(source, filename, mode, *args, **kwargs)

    _mc.ast_compile = _patched_ast_compile
