"""
Asynchronous provenance store.

Backend selection (auto-detected at import time):
  - DuckDB  – preferred; handles Parquet natively and is OLAP-optimised.
  - SQLite  – fallback when DuckDB is not installed.

DataFrame artifacts are persisted as immutable Parquet snapshots on disk,
referenced by path from the metadata DB.
"""

from __future__ import annotations

import json
import threading
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

try:
    import duckdb as _duckdb
    _BACKEND = "duckdb"
except ImportError:
    import sqlite3 as _sqlite3  # type: ignore[no-redef]
    _BACKEND = "sqlite"


# ------------------------------------------------------------------
# DDL
# ------------------------------------------------------------------

_DDL_NODES = """
CREATE TABLE IF NOT EXISTS nodes (
    node_id           VARCHAR PRIMARY KEY,
    history_id        VARCHAR,
    timestamp         VARCHAR NOT NULL,
    pydantic_metadata VARCHAR NOT NULL,
    artifact_path     VARCHAR
)
"""

# DuckDB 1.x supports IDENTITY columns; SQLite uses AUTOINCREMENT.
_DDL_EDGES_DUCKDB = """
CREATE TABLE IF NOT EXISTS edges (
    edge_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id            VARCHAR,
    parent_node_id        VARCHAR,
    child_node_id         VARCHAR,
    transformation_type   VARCHAR
)
"""

_DDL_EDGES_SQLITE = """
CREATE TABLE IF NOT EXISTS edges (
    edge_id               INTEGER PRIMARY KEY AUTOINCREMENT,
    history_id            TEXT,
    parent_node_id        TEXT,
    child_node_id         TEXT,
    transformation_type   TEXT
)
"""

# Migration: add history_id to pre-existing DBs that lack it.
_DDL_MIGRATE_NODES = "ALTER TABLE nodes ADD COLUMN history_id VARCHAR"
_DDL_MIGRATE_EDGES = "ALTER TABLE edges ADD COLUMN history_id VARCHAR"


class StorageBackend:
    """
    Thin async façade over DuckDB / SQLite + Parquet.

    All DB writes are serialised through a single background thread so the
    notebook's execution thread is never blocked by I/O.
    """

    def __init__(
        self,
        db_path: str | Path = "provenance.db",
        artifact_dir: str | Path = "artifacts",
    ) -> None:
        self.db_path = Path(db_path)
        self.artifact_dir = Path(artifact_dir)
        self.artifact_dir.mkdir(parents=True, exist_ok=True)

        # Single-worker executor serialises all writes to the same DB file.
        self._executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="provtrack-io")
        # Block until schema is ready before accepting any async writes.
        self._executor.submit(self._init_schema).result()

    # ------------------------------------------------------------------
    # Public async API
    # ------------------------------------------------------------------

    def save_node_async(
        self,
        node_id: str,
        metadata: dict,
        artifact_path: Optional[str] = None,
        history_id: Optional[str] = None,
    ) -> None:
        """Persist an analysis-state node; returns immediately."""
        self._executor.submit(self._write_node, node_id, metadata, artifact_path, history_id)

    def save_edge_async(
        self,
        parent_id: str,
        child_id: str,
        transformation_type: str,
        history_id: Optional[str] = None,
    ) -> None:
        """Persist a parent→child edge; returns immediately."""
        self._executor.submit(self._write_edge, parent_id, child_id, transformation_type, history_id)

    # ------------------------------------------------------------------
    # Artifact persistence (synchronous – called from the worker thread
    # by runtime.py *before* the async node write so the path is ready)
    # ------------------------------------------------------------------

    def save_artifact(self, node_id: str, df: Any) -> Optional[str]:
        """
        Write *df* to ``<artifact_dir>/<node_id>.parquet``.
        Returns the path string, or None if writing fails.
        """
        path = self.artifact_dir / f"{node_id}.parquet"
        try:
            module = type(df).__module__ or ""
            if "polars" in module:
                df.write_parquet(str(path))
            else:
                # Preserve named indexes (e.g. case:concept:name as row index
                # after groupby().agg()) so case IDs survive the artifact round-trip.
                df.to_parquet(str(path))
            return str(path)
        except Exception:
            return None

    # ------------------------------------------------------------------
    # Read API
    # ------------------------------------------------------------------

    def load_graph(self) -> dict:
        """
        Return all nodes and edges as plain Python dicts.
        Suitable for building a NetworkX DiGraph or a JSON payload for the UI.
        """
        if _BACKEND == "duckdb":
            con = _duckdb.connect(str(self.db_path), read_only=True)
        else:
            con = _sqlite3.connect(str(self.db_path))

        try:
            nodes = con.execute(
                "SELECT node_id, history_id, timestamp, pydantic_metadata, artifact_path FROM nodes"
            ).fetchall()
            edges = con.execute(
                "SELECT parent_node_id, child_node_id, transformation_type, history_id FROM edges"
            ).fetchall()
        finally:
            con.close()

        return {
            "nodes": [
                {
                    "node_id": r[0],
                    "history_id": r[1],
                    "timestamp": r[2],
                    "metadata": json.loads(r[3]),
                    "artifact_path": r[4],
                }
                for r in nodes
            ],
            "edges": [
                {"parent": r[0], "child": r[1], "type": r[2], "history_id": r[3]}
                for r in edges
            ],
        }

    def to_networkx(self):
        """
        Build an in-memory ``networkx.DiGraph`` from the stored provenance DAG.
        Node attributes carry the full deserialized metadata dict.
        """
        import networkx as nx  # optional dependency

        graph_data = self.load_graph()
        G = nx.DiGraph()
        for n in graph_data["nodes"]:
            G.add_node(n["node_id"], **{k: v for k, v in n.items() if k != "node_id"})
        for e in graph_data["edges"]:
            G.add_edge(e["parent"], e["child"], transformation_type=e["type"], history_id=e["history_id"])
        return G

    # ------------------------------------------------------------------
    # Private helpers (run inside the worker thread)
    # ------------------------------------------------------------------

    def _init_schema(self) -> None:
        if _BACKEND == "duckdb":
            con = _duckdb.connect(str(self.db_path))
            con.execute(_DDL_NODES)
            con.execute(_DDL_EDGES_DUCKDB)
            # Migrate pre-existing DBs that lack history_id.
            for stmt in (_DDL_MIGRATE_NODES, _DDL_MIGRATE_EDGES):
                try:
                    con.execute(stmt)
                except Exception:
                    pass  # column already exists
            con.close()
        else:
            con = _sqlite3.connect(str(self.db_path))
            con.execute(_DDL_NODES)
            con.execute(_DDL_EDGES_SQLITE)
            con.commit()
            for stmt in (_DDL_MIGRATE_NODES, _DDL_MIGRATE_EDGES):
                try:
                    con.execute(stmt)
                    con.commit()
                except Exception:
                    pass  # column already exists
            con.close()

    def _write_node(
        self,
        node_id: str,
        metadata: dict,
        artifact_path: Optional[str],
        history_id: Optional[str] = None,
    ) -> None:
        ts = datetime.now(timezone.utc).isoformat()
        payload = json.dumps(metadata, default=str)
        if _BACKEND == "duckdb":
            con = _duckdb.connect(str(self.db_path))
            con.execute(
                "INSERT OR REPLACE INTO nodes VALUES (?, ?, ?, ?, ?)",
                [node_id, history_id, ts, payload, artifact_path],
            )
            con.close()
        else:
            con = _sqlite3.connect(str(self.db_path))
            con.execute(
                "INSERT OR REPLACE INTO nodes VALUES (?, ?, ?, ?, ?)",
                (node_id, history_id, ts, payload, artifact_path),
            )
            con.commit()
            con.close()

    def _write_edge(
        self,
        parent_id: str,
        child_id: str,
        transformation_type: str,
        history_id: Optional[str] = None,
    ) -> None:
        sql = (
            "INSERT INTO edges(history_id, parent_node_id, child_node_id, transformation_type) "
            "VALUES (?, ?, ?, ?)"
        )
        if _BACKEND == "duckdb":
            con = _duckdb.connect(str(self.db_path))
            con.execute(sql, [history_id, parent_id, child_id, transformation_type])
            con.close()
        else:
            con = _sqlite3.connect(str(self.db_path))
            con.execute(sql, (history_id, parent_id, child_id, transformation_type))
            con.commit()
            con.close()
