"""
StorageBackend Protocol — the contract that any provenance storage backend must satisfy.

To implement a new backend (e.g. Postgres, Neo4j, in-memory):
  1. Create a class that provides every method listed here with matching signatures.
  2. Pass an instance of that class wherever StorageBackend is accepted.
  No inheritance required — structural (duck-type) conformance is sufficient.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional, runtime_checkable

from typing import Protocol


@runtime_checkable
class StorageBackend(Protocol):
    """Contract for provenance persistence backends."""

    # ------------------------------------------------------------------
    # Property
    # ------------------------------------------------------------------

    @property
    def artifact_dir(self) -> Path: ...

    # ------------------------------------------------------------------
    # Write — async (fire-and-forget)
    # ------------------------------------------------------------------

    def save_history_async(self, history: Any) -> None: ...
    def save_branch_async(self, branch: Any) -> None: ...
    def save_state_async(self, state: Any) -> None: ...
    def save_step_async(
        self,
        step: Any,
        func_name: str,
        raw_line: Optional[str],
        param_fingerprint: Optional[str],
        history_id: str,
    ) -> None: ...
    def save_operation_async(self, op: Any, op_type: Any, step_category: Any = None) -> None: ...
    def save_agent_async(self, agent: Any, history_id: str) -> None: ...
    def save_env_async(self, env: Any, history_id: str) -> None: ...
    def save_param_values_async(self, pvs: list) -> None: ...
    def save_artifact_records_async(self, artifact: Any, artifact_state: Any, history_id: str) -> None: ...
    def save_delta_async(self, delta: dict, step_id: str) -> None: ...
    def update_history_active_state_async(self, history_id: str, active_state_id: str) -> None: ...

    # ------------------------------------------------------------------
    # Write — sync (blocking)
    # ------------------------------------------------------------------

    def save_pipeline_sync(self, pipeline_id: str, history_id: str, name: str) -> None: ...
    def save_fragment_sync(
        self, fragment_id: str, pipeline_id: str, step_ids: list, position: int
    ) -> None: ...

    # ------------------------------------------------------------------
    # Artifact I/O
    # ------------------------------------------------------------------

    def save_artifact(self, node_id: str, df: Any) -> Optional[str]: ...
    def load_artifact(self, artifact_state_id: str) -> Any: ...
    def load_artifact_path(self, artifact_state_id: str) -> Optional[str]: ...
    def load_output_artifact_state_id(self, output_state_id: str) -> Optional[str]: ...

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def load_graph(self, history_id: Optional[str] = None) -> dict: ...
    def load_states_rich(self, history_id: str) -> list[dict]: ...
    def load_state_detail(self, state_id: str) -> dict: ...
    def load_step_detail(self, step_id: str) -> dict: ...
    def load_branches(self, history_id: str) -> list[dict]: ...
    def load_operations_by_category(self, history_id: str) -> list[dict]: ...
    def load_artifact_lifecycle(self, state_id: str) -> list[dict]: ...
    def load_pipeline_by_name(self, name: str) -> Optional[str]: ...
    def load_pipeline_steps(self, pipeline_id: str) -> list[dict]: ...
    def to_networkx(self, history_id: Optional[str] = None) -> Any: ...
